[package]
name = "auth-service"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.8"
tokio-postgres = "0.7.2"
rust-argon2 = "0.8"
sha2 = "^0.9"
reqwest = { version = "^0.11", features=["json"]}
warp ="^0.3"
clap = "3.0.0-beta.2"
tokio = { version = "1", features=["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
auth-service-api = {version = "*", git = "https://github.com/innexgo/auth-service-api" }
mail-service-api = {version = "*", git = "https://github.com/innexgo/mail-service-api", features=["client"]}
base64-url = "1.4.10"
