[package]
name = "auth-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
tokio-postgres = "0.7.5"
rust-argon2 = "1.0.0"
sha2 = "0.10.1"
reqwest = { version = "0.11.9", features = ["json"] }
warp = "0.3.2"
clap = { version = "3.0.14", features = ["derive"] }
tokio = { version = "1.16.1", features = ["full"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
auth-service-api = {version = "*", git = "https://github.com/innexgo/auth-service-api" }
mail-service-api = {version = "*", git = "https://github.com/innexgo/mail-service-api", features=["client"]}
base64-url = "1.4.10"
