apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-service
        image: auth:1.14.2
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
        ports:
        - containerPort: 80
      - name: auth
        image: auth:1.14.2
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
        ports:
        - containerPort: 80
